<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Spellbook</AssemblyName>
    <RootNamespace>Spellbook</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\spellbook-logo.png" />
  </ItemGroup>
</Project>
